version: '2.0'
services:
#  redis:
#    image: redis:alpine
#    container_name: php-oop-redis
#
#  db:
#    image: mariadb:10.1
#    container_name: php-oop-mariadb
#    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb_large_prefix=1]
#    volumes:
#      - php-oop-database:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=ROOT
#      - MYSQL_DATABASE=pimcore
#      - MYSQL_USER=pimcore
#      - MYSQL_PASSWORD=pimcore

#  node:
#    build: .docker/node
#    container_name: php-oop-node
#    volumes:
#      - .:/var/www/html:cached

#  adminer:
#    image: adminer
#    container_name: php-oop-adminer
#    restart: always
#    volumes:
#      - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/uploads.ini
#    ports:
#      - 2001:8080

  php:
    build: ./.docker/PHP7.1-apache
#    image: dpfaffenbauer/pimcore-docker-php-fpm:PHP7-apache
    container_name: php-oop-php
    volumes:
      - ~/.composer:/root/composer
      - .:/var/www/html:cached
      - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    ports:
      - "2000:80"
#    links:
#     - db:db
#     - redis:redis

#volumes:
#  php-oop-database: